import { redirect } from "@sveltejs/kit";

// StarData: the legacy AI tab is superseded by the portal chat page (`/chat`).
// Redirect all `/-/ai` routes to their portal equivalents, except the citation
// deep-link (`/message/[messageId]/-/open`) which is generated by the backend
// and must keep resolving here.
export const load = ({
  params: { organization, project, conversationId },
  route,
  url,
}) => {
  if (
    route.id ===
    "/[organization]/[project]/-/ai/[conversationId]/message/[messageId]/-/open"
  ) {
    return;
  }

  const base = `/${organization}/${project}/chat`;
  const target = conversationId?.trim() ? `${base}/${conversationId}` : base;
  throw redirect(307, `${target}${url.search}`);
};
